# Generated by Django 4.2.5 on 2023-10-12 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Django_API', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='thumbnail_200',
        ),
        migrations.RemoveField(
            model_name='image',
            name='thumbnail_400',
        ),
        migrations.AddField(
            model_name='image',
            name='thumbnails',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
