# Generated by Django 4.2.5 on 2023-10-13 13:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Django_API', '0002_remove_image_thumbnail_200_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='account_tier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Django_API.tier'),
        ),
    ]
