# Generated by Django 4.2.5 on 2023-10-16 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Django_API', '0006_image_original_image_link_image_thumbnails_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='thumbnails',
        ),
    ]
