# Generated by Django 4.2.5 on 2023-10-16 13:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Django_API', '0007_remove_image_thumbnails'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thumbnail',
            name='parent_image',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='thumbnails', to='Django_API.image'),
        ),
    ]
