# Generated by Django 4.2.5 on 2023-10-18 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Django_API', '0009_image_filename'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thumbnail',
            name='image',
            field=models.ImageField(upload_to='thumbnails/'),
        ),
    ]
