# Generated by Django 4.2.5 on 2023-10-18 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Django_API', '0010_alter_thumbnail_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(upload_to='media/'),
        ),
    ]
