# Generated by Django 4.2.5 on 2023-10-18 21:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Django_API', '0015_alter_tier_thumbnail_sizes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Django_API.customuser'),
        ),
        migrations.AlterField(
            model_name='thumbnail',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Django_API.customuser'),
        ),
    ]
